# Generated by Django 3.2.4 on 2022-12-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friends_selected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
