# Generated by Django 3.2.4 on 2022-12-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='hasAFriend',
            field=models.BooleanField(default=False),
        ),
    ]
